apiVersion: v1
kind: Service
metadata:
  name: megaraid-exporter
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "MegaraidExporter"
spec:
  clusterIP: None
  ports:
    - name: megametrics
      port: 9101
      protocol: TCP
      targetPort: 9101
  selector:
    k8s-app: megaraid-exporter

